services:
  local-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      retries: 3

  minio:
    image: "bitnami/minio:2022.10.21-debian-11-r0"
    environment:
      - MINIO_ROOT_USER=minio123
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DEFAULT_BUCKETS=static:download,ingredientes,receitas
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - postgres-compose-network
