Vagrant.configure("2") do |config|
  config.vm.box = "debian/32bit"
  
  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 9001, host: 9001
  
  config.vm.provision "shell", path: "provisioning/install_docker.sh"
  
  config.vm.provision "docker" do |d|
    d.pull_images "postgres:latest"
    d.run "postgres" do |r|
      r.args = "-e POSTGRES_USER=your_user -e POSTGRES_PASSWORD=your_password -v pgdata:/var/lib/postgresql/data"
    end
  end
end